### ISSUE TITLE
Upgrade RecordLocator to use FormKeys

### ISSUE THREAD

**Issue by Noggog** [Mutagen-Modding/Mutagen#111]
RecordLocator, which is used to quickly parse a file and mark/locate all contained records, was developed pretty early before FormKeys were added.  Would be good to upgrade the system to utilize FormKeys if possible.

This would entail:
- Swapping all FormID usages to FormKey within RecordLocator
- Probably will need to construct a MasterReferenceReader to use to convert FormIDs to FormKeys during processing
- Follow/fix broken code that was using RecordLocator and giving it FormIDs (compiler should let you know where these breaks are)

**Comment by Deigue** [comment]
> Probably will need to construct a MasterReferenceReader to use to convert FormIDs to FormKeys during processing

You mean construct via MasterReferenceReader(modKey) / MasterReferenceReader(modKey, masters) depending on info available, and then using FormKey.Factory(masterRefReader, formID) to generate FormKeys appropriately where needed?
What situations do you ever / would you ever use the standard/simple ctor FormKey(modKey, id) ?

Other than that, might just figure out more as I take a stab. If its not urgent or needed asap by any means, you can assign this one to me.

**Comment by Noggog** [comment]
> What situations do you ever / would you ever use the standard/simple ctor FormKey(modKey, id)

There's a good amount of times you just want to make a FormKey straight up without a reader.  Maybe some tests.  Or places you know the formKey you want specifically:
<https://github.com/tr4wzified/KnowYourEnemyPatcher/blob/8fc960f066502b36ad5a4ab765b6b90090364925/KnowYourEnemyMutagen/Program.cs#L109>
That's just an inversion convenience function that triggers off ModKey, but is essentially `FormKey(ModKey, uint)`

Also the FormKey registry
<https://github.com/Noggog/Mutagen.Bethesda.FormKeys/blob/98b59737d17d4e36e322b94284aed729e56dcdf1/Mutagen.Bethesda.FormKeys.SkyrimSE/Skyrim/Armor.cs#L24>
