### ISSUE TITLE
ConstructibleObject.CreatedObject searches with no scoping

### ISSUE THREAD

**Issue by Noggog** [Mutagen-Modding/Mutagen#123]
Right now, Skyrim's ConstructibleObject.CreatedObject is of type `FormLink<ISkyrimMajorRecordGetter>`.  This means typical lookups will query/read ALL record types, which is usually undesirable.

Unfortunately, this link type isn't scoped in xedit's definition to any subset of record types, which is why its type is so generic.  Perhaps we could do some cursory research on the viable types it can contain?  If it's not too clear, can we at least rule out PlacedObject/Worldspace/Cell and the other heavy ones?

**Comment by Noggog** [comment]
A quick fix would be to just define a LinkInterface `IConstructible` which EVERY record would define EXCEPT Cell/Worldspace/Dialog/Placed objs/maybe a few more.  This likely would still include more than is actually allowed, but would be a good starting point to widdle it to be more accurate later.  Important bit would be that it wouldn't dip into Cells/Worldspace and bring everything to a screetching halt

**Comment by Excinerus** [comment]
COBJ valid targets ARMO WEAP AMMO, MISC KEYM LIGH, ALCH INGR, SCRL BOOK SLGM APPA
These are all the thing that can be in an instantiated inventory (on a loaded ObjectRef/Actor).

Additem(Form,Count) takes all these forms + FormList and LVLI, after testing, COBJs cannot take those however

**Comment by Noggog** [comment]
Glorious!  Thanks for the research.  I'll see about implementing the scoping soon

**Comment by Noggog** [comment]
e95fb1a580172135a929a081a79ea57be19e0943
