### ISSUE TITLE
Some ESL-overriden Worldspace cells are returning the wrong metadata (FormKey.ModKey)

### ISSUE THREAD

**Issue by Deigue** [Mutagen-Modding/Mutagen#132]
Observed two instances (both ESL plugins overriding a Worldspace CELL defined in a master not from the base game)
[Masters : Gray Fox Cowl.esm , arnima.esm ]

> [2308.1][CellEditorIDFixer] Cell EDID arn_BeyondReachBorder in Skyrim.esm (Actual : arnima.esm)
> [2308.1][CellEditorIDFixer] >>> SKIPPED: arn_BeyondReachBorder as Worldspace CELL is currently unsupported.
> [2308.1][CellEditorIDFixer] Cell EDID manny_GF_TeleportSkyrimArea in Skyrim.esm (Actual : Gray Fox Cowl.esm)
> [2308.1][CellEditorIDFixer] >>> SKIPPED: manny_GF_TeleportSkyrimArea as Worldspace CELL is currently unsupported.

When accessing record meta info  i.e: cell?.FormKey.ModKey.FileName , return "Skyrim.esm" instead of expected actual Master.

Assumptions:
- Happening only in ESL overrides. Could be a coincidence, but something I noticed that was differently from other instances working correctly.
- Scope of what is exactly off or wrong. Only noticed FormKey.ModKey while testing, but there could be more data that is a bit off ...

**Comment by Deigue** [comment]
Referential information:
arnima.esm -> [Beyond Reach ](https://www.nexusmods.com/skyrimspecialedition/mods/3008)
Gray Fox Cowl.esm - > [The Gray Cowl of Nocturnal](https://www.nexusmods.com/skyrimspecialedition/mods/4509)

**Comment by Noggog** [comment]
Looking like it is actually from Skyrim.  Gray Cowl just modified the EDID of an existing cell
![image](https://user-images.githubusercontent.com/24981326/96935699-76b36a00-1479-11eb-8884-471d8e2fdf57.png)
