### ISSUE TITLE
When performing some deep copies, some information like FULL (Name) and DESC (Book Text) is missing

### ISSUE THREAD

**Issue by Deigue** [Mutagen-Modding/Mutagen#148]
![image](https://user-images.githubusercontent.com/6877595/98626235-3fe5ac80-22df-11eb-84c3-2b4d7cff602f.png)

![image](https://user-images.githubusercontent.com/6877595/98626246-4a07ab00-22df-11eb-82f5-121ca7414767.png)

Furthermore, this may not be only restricted to BOOK type Records. 

![DLC Scroll Name](https://user-images.githubusercontent.com/6877595/98625795-59d2bf80-22de-11eb-9f11-6c2c1228f346.png)

**Comment by Noggog** [comment]
I think something else is at play.  I did a simple patcher /w
```
foreach (IBookGetter book in state.LoadOrder.PriorityOrder.WinningOverrides<IBookGetter>())
{
    var modifiedBook = book.DeepCopy();
    state.PatchMod.Books.Add(modifiedBook);
}
```
And it came out okay:
![image](https://user-images.githubusercontent.com/24981326/99918622-12303880-2ccd-11eb-95b3-87246d6939f8.png)

Can you try with a minimal load order and see if you see the same?

**Comment by Deigue** [comment]
Ran against ONLY base game plugins and was able to reproduce the missing names,
but this project was last built against Mutagen 0.19.7 and Synthesis 0.10.13.

The only thing I do additionally after DeepCopy() is set the Weight to a particular value, as per the intentions of my ItemWeightCustomizer.

Just thought I would add some background.
Of course, I will upgrade to latest and test more scenarios, once the plugin loading issue is handled and stuff.

**Comment by Noggog** [comment]
Ended up just being that it was run on a development Data folder that was missing its string BSAs
