### ISSUE TITLE
LiveLoadOrder order parsing does not respect RecordHeader's Record Flags (ESM/ESL)

### ISSUE THREAD

**Issue by Deigue** [Mutagen-Modding/Mutagen#160]
![image](https://user-images.githubusercontent.com/6877595/101312762-9d0f4800-3822-11eb-848f-4515b8318c0b.png)

Real Ordering:
![image](https://user-images.githubusercontent.com/6877595/101312821-b7e1bc80-3822-11eb-9197-3263a2c75743.png)

Live Ordering via Synthesis:
![image](https://user-images.githubusercontent.com/6877595/101312850-cf20aa00-3822-11eb-82ce-a09f9cd685f3.png)

This happens due to the fact that LiveOrderListing uses ModKey ByTypeComparer as the sole way of ordering listings:
![image](https://user-images.githubusercontent.com/6877595/101312919-fe371b80-3822-11eb-8a89-55ab4a4ac7b0.png)

We need to have the Record Header information, so that if the ESM RecordFlag is set on a plugin, it is treated on the exact same level as say a ModKey with a .esm extension. 
Similarly, ESL and .esl work slightly differently (not exactly the same).  (.esl) files are forced to be moved to the top of the order ... essentially acting like a .esm file. They do not ALWAYS need to go below a ESM or .esm master.  One is able to place .esl above ESM/.esm with no issues.  ESL just marks a plugin as light plugin, but it doesnt push it to the top of the load order. So the logic should be slightly different between ESL and .esl files.

As such, we will definitely need both Record Flag and ModKey type info in tandem for doing the LiveOrderSorting properly.

**Comment by Deigue** [comment]
https://discord.com/channels/759302581448474626/759344198792380416/785378509446316052
+ some followup notes.

**Comment by Noggog** [comment]
So two parts to this:
- The Mutagen offered "sort my load order" is not correct.  We'll want to upgrade it to consider mod header flags to be more accurate.
- Provided "read my typical load order" systems should not be using that sort ^^

I've removed the usage of the sort, and we can revisit later if we want to improve the sort for other purposes
43c11d8ea42870b97c0444c21197c528a68d1423
