### ISSUE TITLE
Archetype of MagicEffect is not remapped

### ISSUE THREAD

**Issue by erri120** [Mutagen-Modding/Mutagen#188]
https://github.com/Mutagen-Modding/Mutagen/blob/75be6f153aa6c0380a465b5a782c64f0276518b4/Mutagen.Bethesda.Skyrim/Records/Major%20Records/MagicEffect_Generated.cs#L2858-L2882

`obj.Archetype` should be remapped here because some magic effects like the "Summon Creature" Archetype reference another record which is not being remapped:

https://github.com/Mutagen-Modding/Mutagen/blob/75be6f153aa6c0380a465b5a782c64f0276518b4/Mutagen.Bethesda.Skyrim/Records/Major%20Records/MagicEffectArchetype.cs#L60

**Comment by erri120** [comment]
Kinda related to #172

**Comment by Noggog** [comment]
Fixed in 182d60e5dbb75a035bdab99bca2511843ed24ddb
