### ISSUE TITLE
IArchiveReader.TryGetFolder inconsistent, and inadequate for filtered iteration of files

### ISSUE THREAD

**Issue by SteveTownsend** [Mutagen-Modding/Mutagen#196]
The BA2 and BSA implementations are inconsistent. BSA does exact match on the directory, BA2 uses StartsWith semantics to build a list of matching files in a folder wrapper. Neither is broadly useful for directory tree traversal. 
For NIF file transformation I need the ability to filter files whose paths match the entries in a collection. To this end I've locally exposed the _Files_ property in _IArchiveReader_, then I can do this:
```
                // Introspect BSAs to locate meshes not found as loose files. Dups are ignored - first find wins.
                // ModKey parameter appears immaterial.
                foreach (var bsaFile in Archive.GetApplicableArchivePaths(GameRelease.SkyrimSE, ScriptLess.PatcherState.DataFolderPath, new ModKey()))
                {
                    var bsaReader = Archive.CreateReader(GameRelease.SkyrimSE, bsaFile);
                    foreach (var bsaMesh in bsaReader.Files.Where(candidate => bsaFiles.ContainsKey(candidate.Path)))
                    {
                    }
                }
```
I can make a PR with this change if you are OK with it.
```
    public interface IArchiveReader
    {
        bool TryGetFolder(string path, [MaybeNullWhen(false)] out IArchiveFolder folder);
        IEnumerable<IArchiveFile> Files { get; }
    }
```

**Comment by Noggog** [comment]
Yeah, definitely.  The current interface was a minimal exposure just to get the strings system working.  I imagine we could flesh out the exposure/functionality on the interfaces a lot.

Adding a file enumerator sounds like a decent start that won't be harmful to expose

ModKey is sort of vestigial parameter.  For a while I thought that supplying the ModKey would allow the internal systems better locate the applicable BSAs, but realized that wasn't really the case.  I have to do some more research on what's allowed versus not.  Like, if the ModKey is from the implicit listings, then look in the stock BSAs.  If not, then only look for a BSA file that matches the mod name?  I have to make sure that's accurate.  But once that's sorted out, the ModKey parameter will be useful again

**Comment by Noggog** [comment]
File enumeration loop is in and will be in the next release.    Is this API good?  Or is there some other ideal stretch goal exposure pattern you can think of that would be better?

**Comment by SteveTownsend** [comment]
I think this small change provides a lot of power, when combined with LINQ.
Models are effectively synonymous with the unique filename combined with
last override, and the paths are intuitive. Nothing else I need right now
but I'll let you know if anything else comes up in the AllGUD porting.
