### ISSUE TITLE
Print ModKey / ESP name when throwing exceptions about incorrect data formats and the like

### ISSUE THREAD

**Issue by tr4wzified** [Mutagen-Modding/Mutagen#199]
Errors like `[20.5][AI-Overhaul-Patcher] ---> System.ArgumentException: Read in data that was not a GRUP` would be a lot more useful if they printed the ModKey that has this specific weird record. In this particular case the user has 825 plugins, so good luck finding the bad one. Ideally even printing the individual record FormKey would be very useful :)

Found the string in StreamHeaderMixIn.cs, but looks like it's very low level so not sure if it's actually possible, but it'd be quite handy for debugging purposes.

**Comment by Noggog** [comment]
648af2d8b189e1f1b9ebf98aee389cbe2458e4a4
a40d4b2e7c30d7f7af4e1fcd86c86b7eff7b6fc9
67dc7b1ae1a1302ace2af6ea17b6ef241bebfc85

**Comment by tr4wzified** [comment]
:heart: That's a lot of changed files, hahaha
