### ISSUE TITLE
Compilation

### ISSUE THREAD

**Issue by tstavrianos** [Mutagen-Modding/Mutagen#2]
I've been trying to compile the Mutagen.Bethesda.Generation project (I wanted to see if I can start filling in some of the skyrim records) but haven't had much luck.

The Mutagen.Bethesda.Skyrim compiles without issues, once I clone the other required repos.

Any tips of how to make it work, or is there a binary available that could be used to fill in a generate the missing record types?

**Comment by Noggog** [comment]
Heya!  We sorted out the issue talking on the side in discord, but I'll post a little bit for any others coming through later:

I need to streamline the cloning/syncing systems a bit as the project gets closer to usability.  Will be working on updating the docs, and keeping master branch tip in better shape moving forward.

His issue was just that the master commit had pointers to parent repos that did not exist (as in not yet pushed to their respective repos).  I pointed him to an older commit that referenced existing commits on the parent repos, and he was able to build.  Hopefully this won't be an issue once procedures become more rigid going forward
