### ISSUE TITLE
"Previous override" support?

### ISSUE THREAD

**Issue by focustense** [Mutagen-Modding/Mutagen#201]
I just learned about Mutagen and have started working to convert a big pile of XEditLib P/Invoke code. One important thing that I haven't been able to find - though that doesn't mean it's not there, I might just be missing it - is the PO pointer that XEdit provides. I assume that the `Parent` property actually points to the master record, since there isn't an actual `Master` property.

Specifically, I use this to check for ITPO, which is important for my use case. I suppose I could do something like scan through the entire load order searching for the last previous record with the same key, but it seems inefficient by comparison... I have to do this on potentially several thousand records.

AFAICT the `Equals` operator already does a deep comparison, so all I need is an efficient way to find the PO record to compare to. Does it already exist and I'm missing the obvious, or is it not supported yet/ever?

**Comment by theSkyseS** [comment]
For finding PO you could use something like this snippet:
```csharp
//this is some formlink that you can get either from record or from FormKeys
var formLink = ... 
var overrides = formLink.ResolveAll(state.LinkCache).Take(2).ToList();
//overrides then contains winning override at 0 position and previous override at 1st.
```
If you also want to know which override comes from which mod you can use `ResolveAllContexts<>` instead of `ResolveAll`.
You can find "FormKeys" [here](https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys).

**Comment by Noggog** [comment]
Hey! Good question!   Going to convert this issue to a discussion FAQ, so others can see it in the future.

Thanks @theSkyseS, you're right on the money.  LinkCaches + ResolveAll is what you're looking for.

I've been filling out the docs, so I just took the opportunity to get the relevant ones complete:
https://github.com/Mutagen-Modding/Mutagen/wiki/LinkCache
https://github.com/Mutagen-Modding/Mutagen/wiki/Previous-Override-Iteration
