### ISSUE TITLE
Make BsaReader case-insensitive

### ISSUE THREAD

**Issue by focustense** [Mutagen-Modding/Mutagen#209]
Submitting this as a feature request, not a bug report.

While debugging an issue where `TryGetFolder` was always returning false, I figured out what was happening by inspecting the non-public members: the `_foldersByName` keys are all lowercase, whereas the generated paths I was supplying (sometimes based on actual physical filenames, or file paths in an ESP) were mixed-case.

BSA paths are always lowercase, as per spec, but this Mutagen behavior was surprising to me because other tools, as well as Skyrim itself, do not require the _requested_ paths to be lowercase, only the _stored_ paths. To be consistent with the games themselves, and to avoid confusing users of the library who pull paths out of a plugin record and can't figure out why they don't resolve using `TryGetFolder`, I suggest making the lookups case-insensitive.

It would be pretty trivial to do this, only needing to change this line:

```c#
var ret = new Dictionary<string, BsaFolderRecord>();
```

to:

```c#
var ret = new Dictionary<string, BsaFolderRecord>(StringComparer.OrdinalIgnoreCase);
```

or one of the other `*IgnoreCase` comparers.

**Comment by Noggog** [comment]
Thanks!

567f69e873fa29d9f80c799a3136a4aa04fe2a73
