### ISSUE TITLE
Support writing /w Compression flag on

### ISSUE THREAD

**Issue by Noggog** [Mutagen-Modding/Mutagen#235]
Right now mutagen doesn't export /w any compression mechanics.  Just not high priority feature as all it does is save space on-disk, as far as I'm aware.  We can eventually add it for completeness

The main aspect to getting this done will be doing any research to know that we're using the correct compression when writing out.  Not sure either way if that would cause problems, but theoretically could.

-------------

In the meantime, if you want to export a mod that has compressed records, this is an easy fix to make them all not compressed before exporting:
```cs
foreach (var rec in mod.EnumerateMajorRecords())
{
    rec.IsCompressed = false;
}
```

**Comment by Noggog** [comment]
In the meantime, if you want to export a mod that has compressed records, this is an easy fix to make them all not compressed before exporting:
```cs
foreach (var rec in mod.EnumerateMajorRecords())
{
    rec.IsCompressed = false;
}
```

**Comment by ghyujkilop** [comment]
I might be wrong in saying this, but when using something like [Remove Landscape Vertex Color](https://www.nexusmods.com/skyrimspecialedition/mods/64132) the loading time is DRASTICALLY increased. And if you look at the records it's only removing vertex colors. However, when you compare the data size difference https://i.imgur.com/OBDUIMW.png you can see that this would be a primary cause of wildly increased loading times. Could this priority of being added be raised due to increased loading times?

**Comment by Noggog** [comment]
Good points.  Thanks for the feedback.  Will be seeing if/when I can slide in the feature

**Comment by JMPZ11** [comment]
What is the status on this issue?

For starfield, I can't really use the output if it doesn't compress the cells, as I think Starfield always compresses them.

It isn't a huge deal, but it does mean I must open the output in xedit to fix the cells, so I can't really automate yet.

Thanks!

**Comment by Noggog** [comment]
I think the main blocker is just researching the proper compression choice, and finding the right C# library and call to use to get a resulting compression that the game can read.   I know there's a few out there, so I didn't want to just slap any zip call I could find on the system

If anyone has any research on the proper compression choice to use, that'd help move it along!

**Comment by JMPZ11** [comment]
> I think the main blocker is just researching the proper compression choice, and finding the right C# library and call to use to get a resulting compression that the game can read. I know there's a few out there, so I didn't want to just slap any zip call I could find on the system
> 
> If anyone has any research on the proper compression choice to use, that'd help move it along!

How does mutagen read the cells that are compressed? Could that provide insight into the algorithm being used maybe?

**Comment by Noggog** [comment]
Here is the file that is doing the work, currently
https://github.com/Mutagen-Modding/Mutagen/blob/dev/Mutagen.Bethesda.Core/Plugins/Binary/Streams/Decompression.cs#L71

The main question at hand is whether this Zlib library able to decompress many incoming alternatives.. but the reverse might not be true.. where it's exporting a specific compression algo that the game might expect

It might not be a problem at all, but I would want to do some tests to show that before pushing out an update that suddenly starts CTDing peoples mods.   

---------

Avenues for solution that I see:
- Googling/researching around to see if modders have documented any compression requirements the game has
- Turning on the compression in Mutagen on a side branch, and making a test CLI that imports/re-exports a mod.  If we run that on a mod /w say, some compressed NPCs, and it loads up in skyrim after mutagen has passed it through its compression systems, then that's another indicator that it's good to go

**Comment by JMPZ11** [comment]
I asked the xedit folks and got this:

"that would be zlib or lz4"
"Same as in tes4"


Does this help? Sorry for the delay responding - this is the one thing I'm aware of that causes the output to require manual correction for Starfield.

Is zlib able to be configured with verbose logging maybe? Or are the .net binding capable of reporting the compression used?

If I could just get a sample of the data being decompressed I'd be happy to do the legwork -- I just don't know how to extract the relevant bits to test myself...

**Comment by dbt0815** [comment]
> 
> foreach (var rec in mod.EnumerateMajorRecords())
> {
>     rec.IsCompressed = false;
> }

where do i put this? :)

**Comment by d3m0n0id** [comment]
> > foreach (var rec in mod.EnumerateMajorRecords())
> > {
> > rec.IsCompressed = false;
> > }
> 
> where do i put this? :)

+1

would love to have my patcher not argue with me about using common patches, really slowing down actually getting to *play* my almost-finished modbuild

**Comment by Noggog** [comment]
Not sure im understanding your questions @dbt0815 and @d3m0n0id 

This issue has been marked closed, as Mutagen now is able to write mods with compression enabled.

Are you having issues when doing so in your own program's you're writing?  Or are you reporting a downstream issue, such as using Synthesis's patcher pipeline?

**Comment by d3m0n0id** [comment]
> Not sure im understanding your questions [@dbt0815](https://github.com/dbt0815) and [@d3m0n0id](https://github.com/d3m0n0id)
> 
> This issue has been marked closed, as Mutagen now is able to write mods with compression enabled.
> 
> Are you having issues when doing so in your own program's you're writing? Or are you reporting a downstream issue, such as using Synthesis's patcher pipeline?

Have had that error several times with the GrassFPS and Navmesh patches tonight. But it's incredibly inconsistent so I have no idea what's causing it. So was just wondering where to put that code blurb so I could avoid the issue in the future.

**Comment by Noggog** [comment]
I imagine you're speaking about running a Synthesis patch pipeline?  This repo/issue is a bit upstream of [Synthesis](https://github.com/Mutagen-Modding/Synthesis).

[Here's an FAQ](https://github.com/Mutagen-Modding/Synthesis/discussions/544) that might relate to your issue

Also try making sure your patchers are running against the latest versions, as [outlined here](https://mutagen-modding.github.io/Synthesis/Versioning/#recommended-setup)

**Comment by har-nick** [comment]
Just a notice for anyone running into this issue with patches that require a matched Synthesis version, or just by cosmic chance, I've found the only (known to me) fix to be using [SSE Decompress Records](https://www.nexusmods.com/skyrimspecialedition/mods/86312) on your load order, including `Skyrim.esm` despite the mod author's recommendations.

It _does_ work, but it's an extra step your Skyrim tooling, and you may need to run it multiple times if a newly-installed mod has a compressed plugin.

**Comment by Noggog** [comment]
@har-nick 
Thanks for the tip!  Do you know which patchers require match still?   The number should be less and less as time goes on.  Maybe just need to do the small tweak to get them up to speed.

Also, I might update Synthesis to weave older patcher compression a bit better sometime

**Comment by har-nick** [comment]
Thanks for the quick reply ;)

Off the top of my head, [HighPolyHead-RaceMenuPatcher](https://github.com/EzioTheDeadPoet/HighPolyHead-RaceMenuPatcher) and [Missing-Encounter-Zones-Patcher](https://github.com/ReaperAnon/Missing-Encounter-Zones-Patcher).

Honestly, I'd learn to patch them myself but I'm allergic to dotnet :p

**Comment by Noggog** [comment]
Hmm, high poly head works fine on latest
<img width="494" height="415" alt="Image" src="https://github.com/user-attachments/assets/4e05a8c3-6450-4e2b-b44d-e25e7066ec74" />

[Recommended pattern](https://mutagen-modding.github.io/Synthesis/Versioning/#recommended-setup)

that encounter zone patcher has issue, though, for sure.
[Opened a PR with them](https://github.com/ReaperAnon/Missing-Encounter-Zones-Patcher/pull/2)

You can opt to point your patcher to my fork which has the changes in the meantime
https://github.com/Noggog/Missing-Encounter-Zones-Patcher

**Comment by KylerN45** [comment]
Issue persists in Synthesis 0.35.5, despite being closed.

<img width="1582" height="1000" alt="Image" src="https://github.com/user-attachments/assets/f536f113-89a4-4bbb-9894-45c6b0fbe25a" />

**Comment by Noggog** [comment]
Each patcher is able to target different synthesis/mutagen versions.   The version at the top right is just what the UI's version is.

I would double check what version that patcher is targeting, and maybe up it to use the latest
https://mutagen-modding.github.io/Synthesis/Versioning/#recommended-setup
