### ISSUE TITLE
WaterReflectionBinaryOverlay.Type ArgumentOutOfRangeException when empty

### ISSUE THREAD

**Issue by Benna96** [Mutagen-Modding/Mutagen#249]
When a water reflection's type is empty, such as in records `0015F7:Dawnguard.esm` and `0015F2:Dawnguard.esm` in SkyrimSE, attempting to access the water reflection's Type field throws an ArgumentOutOfRangeException.

The specific error when hovering over the Type field in Visual Studio's watch is:
```C#
'(new System.Linq.SystemCore_EnumerableDebugView<Mutagen.Bethesda.Skyrim.Internals.WaterReflectionBinaryOverlay>(((Mutagen.Bethesda.Skyrim.Internals.PlacedObjectBinaryOverlay)modded).Reflections).Items[0]).Type' threw an exception of type 'System.ArgumentOutOfRangeException'
```

The stack trace is
```C#
   at System.ThrowHelper.ThrowArgumentOutOfRangeException()
   at System.ReadOnlySpan`1.Slice(Int32 start, Int32 length)
   at Mutagen.Bethesda.Skyrim.Internals.WaterReflectionBinaryOverlay.get_Type()
```

The issue only affects WaterReflectionBinaryOverlay. An equivalent WaterReflection's type is 0.

Edit: Forgot to mention versions.
I was using Mutagen.Bethesda v0.29.2 and Mutagen.Bethesda.Synthesis v0.18.3 when discovering the bug.
Updated to v0.33.2 and v0.20.4, respectively. Issue still occurs,

**Comment by Noggog** [comment]
8c5ebc860f68e302451a36a0e0dbc871786e9fa6
