### ISSUE TITLE
LLists with more than 255

### ISSUE THREAD

**Issue by Noggog** [Mutagen-Modding/Mutagen#305]
Someone reported a bashed patch they had with a LList with more than 255 entries.  The count listed zero, and xedit wouldnt edit the count to be anything but zero.   

They say Skyrim loads with it, but haven't tested if the LList spawns/works.

Potentially an test if that's a valid mod state, and if so, handle and allow LLists to be greater than 255 /w the count set to zero.

**Comment by monyarm** [comment]
I can confirm that i've seen such LLists in both FNV and Skyrim, and from what I've seen they seem to work just fine.
