### ISSUE TITLE
<Error: Unknown lstring ID ########> and strings related game crash in main menu on startup because this.

### ISSUE THREAD

**Issue by TokcDK** [Mutagen-Modding/Mutagen#352]
Updated Synthesis with latest muthagen and found that sometime begin to appear Unknown lstring records in patch file.
First I noticed it in cnam- description records of books when applied the [patch](https://github.com/TokcDK/SynFixBOOKRecordTypes)
(but for tests need to comment temp fix line `if (book.Description != null) book.Description = null;`)
It looks like this:
![2022-07-27_100032](https://user-images.githubusercontent.com/5264340/181165160-49d90cf5-ed63-45c5-88fc-6a90a3d82961.jpg)

After I created patch with this unknown records game started crashing in main menu after startup. Later I noticed same unknown records in weapon record changes created by other patch.

upd:
Records noticed in changes of Skyrim.esm and Dawnguard.esm records which is not changed by other mods. For example here is record which was changed by usleep and there is no unknown record added:
![2022-07-27_101653](https://user-images.githubusercontent.com/5264340/181166985-e7496b13-3c85-4dc8-9e02-df6d647c8d0e.jpg)
only when record strings get from string file.

Ofcourse game is not possible to run with any patch where is kind of unknown records and almost impossible to find them all and remove manually in thousands of records.

**Comment by TokcDK** [comment]
@Noggog
I tested different versions of Mutagen.Bethesda and found that v36.0 have no the bug and it appears in 36.0.1 (pr001 already have it). Patch can be applied with no bug when used versions 0.22.1+0.36.0. Hope it will help to find breaking change faster.

**Comment by Noggog** [comment]
Have you tried using the newest setups?  0.36 is still pretty old
0.39.2 is the latest, and you'd want to use it alongside the newest synth UI.  If you're using a language other than english, maybe look around
https://github.com/Mutagen-Modding/Synthesis/wiki/Language-Settings

**Comment by TokcDK** [comment]
> Have you tried using the newest setups? 0.36 is still pretty old 0.39.2 is the latest, and you'd want to use it alongside the newest synth UI. If you're using a language other than english, maybe look around https://github.com/Mutagen-Modding/Synthesis/wiki/Language-Settings

I noticed the bug after updated to 0.23.7+0.39.2

**Comment by Noggog** [comment]
are you running with a language other than english?

**Comment by TokcDK** [comment]
Sorry for not mentioned versions in first post. Just supposed that latest versions is always using by default. In my case Im using Profile versions setup and usually it was set to Latest and when some patcher was not compiling I just created fork and fixed error and then added fork to list but now this unknown records can appear for any patcher and I need to set manually versions to 0.22.1+0.36.0

**Comment by TokcDK** [comment]
> are you running with a language other than english?

Yes

**Comment by Noggog** [comment]
Can you take a screenshot of your language settings in synthesis profile UI?  What UI version are you using?

**Comment by TokcDK** [comment]
> Can you take a screenshot of your language settings in synthesis profile UI? What UI version are you using?

All settings are same as was posten in issue #270 I have Localize checkbox checked and selected language. As metioned unknown lstrings appeared only for records where strings are from strings file and not overwried by any mod.

**Comment by Noggog** [comment]
Ah, I think I reproduced.  Wasn't until I realized we were dealing with LE that I tested over there and am seeing what you're seeing:
![image](https://user-images.githubusercontent.com/24981326/181690307-f52ddc88-87ad-4768-a71b-20c9ad2ad91a.png)

Taking a look

**Comment by TokcDK** [comment]
Oh, it is in english also as I see.

**Comment by Noggog** [comment]
Let me know if Mutagen v0.39.3 helps at all

**Comment by TokcDK** [comment]
Yes, in 0.39.3 it fixed now. I dont see unknown lstrings in books patch. Only noticed that Synthesis writes in console mutagen: 0.39.2 version.

**Comment by TokcDK** [comment]
Bug is fixed in Mutagen 0.39.3. Close then.
