### ISSUE TITLE
Worldspace SubCells not enumerating

### ISSUE THREAD

**Issue by cram42** [Mutagen-Modding/Mutagen#407]
`var ws = Mutagen.Bethesda.FormKeys.SkyrimSE.Skyrim.Worldspace.WhiterunWorld.Resolve(state.LinkCache);`

`ws.SubCells` only contains 1 Block (coordinate 0, -1).
That block's `Items` only contains 1 Sub-Block (coordinate 0, -1).
That sub-block's `Items` only contains 1 Cell ("WhiterunSkyforge" "01A272:Skyrim.esm")

Am I forgetting something or is it currently not possible to enumerate sub-blocks and cells from a worldspace?

**Comment by Noggog** [comment]
I dont have a wiki about it yet (I'll write one up), but what you're interacting with is the fact that certain lists of records "accumulate" vs "override".  Worldspace cells, Dialogs, etc.   A mod can override a worldspace and just list one cell that they wanted to tweak, and this doesn't remove all the other cells from the Worldspace, as it's additive.  They just wanted to tweak that one cell, but don't/shouldn't need to relist all the other cells.

This changes how WinningOverride works, as the winning override for a Worldspace won't necessarily contain all the cells, it'll just contain the cells that last mod wanted to change.  To get a full sense of all the cells a worldspace has, you need to reach back into every mod that exists and see what cells they define.  You can do this via [ResolveAll](https://github.com/Mutagen-Modding/Mutagen/wiki/Previous-Override-Iteration#resolveall).  You'd then need to accumulate all the cells you see to get the full picture.  Mutagen might offer a more formalized way of this style of accumulation at some point, but doesn't offer that currently.

**Comment by cram42** [comment]
Ah, that makes so much sense now!
Thanks for the help.
