### ISSUE TITLE
IKeyworded.HasKeywords

### ISSUE THREAD

**Issue by Noggog** [Mutagen-Modding/Mutagen#415]
Right now it only offers convenience extension methods for single keyword checks.  Would be nice to be able to pass in a collection.

**Comment by MarkKoz** [comment]
Do we also want to cover the extension methods that do cache lookups?

**Comment by Noggog** [comment]
> Do we also want to cover the extension methods that do cache lookups?

Hmm, don't think so.  I think that'd have to be studied a bit more on how that API would look as maybe a different issue.  Since it's returning many values, of which many could fail it's not straightforward what the call should look like or what it should return

**Comment by MarkKoz** [comment]
I took a stab at it in my PR — it only returns a single value, though I'm happy to change or remove it for now if that's not what you had in mind.
