### ISSUE TITLE
Fallout4 Object Modification with no DATA

### ISSUE THREAD

**Issue by Noggog** [Mutagen-Modding/Mutagen#422]
Unknown systems should be able to handle it?

**Comment by D3m0nK1113r99** [comment]
![Screenshot_20230301_111227](https://user-images.githubusercontent.com/123758421/223241923-e5171150-df1d-46fe-a057-a7df174dd15e.png)

**Comment by D3m0nK1113r99** [comment]
![Screenshot_20230301_111227](https://user-images.githubusercontent.com/123758421/223243825-47144ad5-9e33-4991-84c9-e7e91c8cad95.png)
