### ISSUE TITLE
Type of Rank property in RankPlacement classes

### ISSUE THREAD

**Issue by gavrant** [Mutagen-Modding/Mutagen#426]
In Mutagen, `Rank` property of `IRankPlacementGetter` and `IRankPlacement` is a `byte` (unsigned 8-bit int), while everything else - Creation Kit, xEdit, Skyrim engine itself, treats the rank as a signed value. In faction membership checks, the game considers a negative rank as "NOT a member of the faction". And there's plenty of NPCs in Skyrim with -1 ranks (for example, Mjoll actor or basically any other potential follower). This led to a bug in my code when a `factionEntry.Rank >= 0` check turned out to be always true, and I had to replace it with an unobvious `factionEntry.Rank < 128`.

Don't know if it's also true for the rest of supported games besides Skyrim.

**Comment by Noggog** [comment]
Ah, seems like a typo, then.  Checking xEdit docs, it's indeed a signed byte, where Mutagen currently has it as unsigned.  Thanks for opening the issue!

**Comment by gavrant** [comment]
I just found another set of classes with an unsigned Rank - PerkPlacement ones, but I don't know if they need to be signed too.

**Comment by Noggog** [comment]
I checked that one and I think it's supposed to be unsigned, at least according to xedit
