### ISSUE TITLE
Confusing behavior of HoursUntilReset property in StoryManagerQuest

### ISSUE THREAD

**Issue by gavrant** [Mutagen-Modding/Mutagen#427]
I was setting the reset period of an Actor Dialogue event quest to 72 hours with `qentry.HoursUntilReset = 72.0f;` code. To my surprise, xEdit displayed that as 0.125 hours. After comparing other non-zero quest reset periods in xEdit to their values in Mutagen I figured out that `HoursUntilReset` in Mutagen stores a number of hours multiplied by some magic number - 576, and I need to write this: `qentry.HoursUntilReset = 72 * 576;` for it to work correctly. So, if this 576 thing is just a weird trait of the game engine and has no actual practical uses, I would like to suggest to hide this unobvious and confusing behavior under the hood. That is, Mutagen deep inside would divide the reset period by 576 on reading it from a file and multiply by 576 on writing to a file, exposing only the clean value without the 576 multiplier as a result.

Just in case, the game is Skyrim.

**Comment by Noggog** [comment]
Thanks for all the reports!  We do testing that we can import/export the same data, but sometimes scaling/signing errors can fly under the radar, as those don't show up in those passthrough tests.

I think the x24 multiplier is just being applied in the reverse direction.  So to compensate you have to apply it twice 24 * 24 = 576

Will get it fixed!

**Comment by gavrant** [comment]
Oh, I thought hours * 576 was the way Skyrim stores this particular value in .esm's and .esp's. So I guess, all the hours are converted to days, including, for example, the reset hours in dialogue infos (IDialogResponses)? 

My eye caught one thing in this ticket commit though: a 0.041666668f multiplier is used in some conversions instead of a 24,0f divider. I believe this is responsible for the small rounding errors I keep seeing in the reset hours in dialogue infos: I set them to 24.0 in Mutagen, Creation Kit shows them as 23.99. It's not a huge problem obviously, but is a little bit irritating, and I think dividing by 24 instead of multiplying would help to avoid this because 24 could be accurately represented in a float while 1/24 couldn't. Should I open a new issue for this?

**Comment by Noggog** [comment]
This issue is slightly related https://github.com/Mutagen-Modding/Mutagen/issues/181
But this is more about removing import/export jitter on repeated read/writes of unchanged data

I think what you're suggesting is treating multipliers/divisors differently during translation.  yeah, i think that's a good idea and worth opening an issue for
