### ISSUE TITLE
On precise conversion of mod file values to hours

### ISSUE THREAD

**Issue by gavrant** [Mutagen-Modding/Mutagen#428]
This issue is a continuation of my idea from #427 about more precise conversion of time values from mod files to "human-workable" hours and back. It might be also related to #181. The issue is broken into 2 "sub-issues" because it seems they require somewhat different solutions.

Please note that the "ideal solutions" I suggest below are more like speculations based on my intuition and coding experience, and Bethesda could do things differently in the games or Creation Kit. In that case, the "Bethesda way" must take precedence over my theories, no matter how good they could be.

### Sub-issue 1: Float days to hours and back (HoursUntilReset in Story Manager Nodes)
In commit https://github.com/Mutagen-Modding/Mutagen/commit/66390a489ce8ce3c28b0b8069783b6fb4765bb16 for #427 I noticed one thing: in some places, to convert hours to day, the value is multiplied by 0.041666668f instead of being divided by 24.0f. I think it might introduce an occasional rounding error, even when the value is not changed after being read from a mod file.

A quick and dirty example code of "divide vs multiply" back-and-forth conversion to prove that:
```
CultureInfo invc = (CultureInfo)CultureInfo.InvariantCulture.Clone();
invc.NumberFormat.NegativeSign = "-";
invc.NumberFormat.NumberDecimalSeparator = ".";
for (int i = 1; i < 50; i++)
{
    Single x = ((Single)i) / 2.0f;
    Console.WriteLine("x = {0}", x.ToString("G9", invc));
    var x1 = x / 24.0f;
    Console.WriteLine("   x1 = x / 24 = {0}", x1.ToString("G9", invc));
    var x2 = x * 0.041666668f;
    Console.WriteLine("   x2 = x * 0.041666668f = {0}", x2.ToString("G9", invc));
    Console.WriteLine("   x1 == x2: {0}", (x1 == x2));
    var x12 = x1 * 24.0f;
    Console.WriteLine("   x1 * 24 = {0} ({1})", x12.ToString("G9", invc), (x12 == x));
    var x22 = x2 * 24.0f;
    Console.WriteLine("   x2 * 24 = {0} ({1})", x22.ToString("G9", invc), (x22 == x));
}
```

If you run this code, you may notice that for some x's (2.5, 3.5, 5, ...) `/ 24.0f` and `* 0.041666668f` produce slightly different results. Most of the times it does not affect the result of the "back conversion" (multiplying by 24.0f), but for a few x's (3.5, 7, 12.5, ...) `/ 24.0f * 24.0f` gets the exact original x while `* 0.041666668f * 24.0f` gets a different value. I would say this happens because 0.041666668f is not the exact representation of 1 / 24, so it introduces a tiny error in calculations.

My suggestion: whenever Mutagen converts a mod file "days" value to hours and back, always use `/ 24.0f` instead of `* 0.041666668f` (and `* 24.0f` instead `/ 0.041666668f`, if this happens anywhere).

### Sub-issue 2: ResetHours in dialogue infos (DialogResponses)
Recently I had an issue when setting ResetHours of DialogResponses to 24.0f in Mutagen: Creation Kit displayed that as 23.99. At first, I thought it's the same "days to hours" conversion problem, but it turned out to be a somewhat different matter. To quote UESP, 

> ENAM - ResetTime - uint16 - Hours until reset. Scaled: 0 = 0 hours, 0xFFFF = 24 hours.

 So the formula for this conversion would be: `hours = (resetTime / 65535) * 24`. As far as I can see, currently Mutagen converts this value with a double-typed 0.0003663003663003663 multiplier (which is a not-so-accurate representation of 24 / 0xFFFF).

My "perfectly accurate conversion pseudo-code" here would be this:
`hoursValue = ((float) (24 * ((int) rawValue))) / 65535.0f`
and
`rawValue = (uint16) ((hoursValue * 65535.0f) / 24.0f)`
(or maybe even `rawValue = (uint16) ( ((int) (hoursValue * 65535.0f)) / 24 )`)
When and where values are converted from one type to another, and the order in which they are multiplied and divided, matter here. And replacing 65535 and 24 with a single constant must be avoided because it would reintroduce rounding errors in this case. And perhaps use double instead of float for additional precision.

### Final note
I do not touch other time values here yet because, for example, the duration of packages is stored as minutes and would require a yet another different conversion formula.

**Comment by Noggog** [comment]
Thanks for the detailed write up

Yeah, sounds like the big issue is the standardization of all divisor/multiplier definitions to be multiplier when applied "under the hood".  This is what means a `/ 24` is instead treated as a `* .041666668f ` in actual application.

I think we can improve the code generation to apply the divisor definitions more directly as division operations.   

Perhaps additionally, we can have the definitions take more complex multiplier strings in general, allowing us to write in the definition `65535f / 24f`, and inject that directly into the code rather than the precalculated combination

**Comment by gavrant** [comment]
> Perhaps additionally, we can have the definitions take more complex multiplier strings in general, allowing us to write in the definition 65535f / 24f, and inject that directly into the code rather than the precalculated combination

I think "this is the way", as mandalorians say. Not only it would make the calculations more accurate, it would also make the code more readable and easier to understand. Compare, for example, the current "single multiplier" way in DialogResponseFlags_Generated.cs:
`Single ResetHours => ... GetFloat(..., FloatIntegerType.UShort, 0.0003663003663003663);`
to the discussed "mutliplier and divisor" way:
`Single ResetHours => ... GetFloat(..., FloatIntegerType.UShort, 24.0, 65535.0);`
While `0.0003663003663003663` looks like some mysterious magic number, at least to me without looking into UESP, `24.0, 65535.0` makes way clearer what's going on here without UESP or something. In the latter case one can make a pretty educated guess that 24 is the number of hours in the day and 65535 is the max value that could be stored in uint16.

Also, the simpler "days to hours" conversion is technically just a special case of the "multiplier and divisor" way, with the multiplier being 1.0. But I'm wary of applying a redundant arithmetic operation to float and would go with a separate "divisor only" function for that (not so long ago I was bitten by a cosine value greater than 1.0 in a python script, so for now I'm scared of floats, even if they are double floats).
