### ISSUE TITLE
Float to Uint Conversion on Write a Mod File

### ISSUE THREAD

**Issue by gavrant** [Mutagen-Modding/Mutagen#429]
Using IDialogResponses.Flags.ResetHours as a testing playground in 0.41, I found the following issues:

1. `ResetHours = 24.0f` still results in 23.99 in Creation Kit. And as far as I can see in a hex editor, the actual written value (in byte order) is F0-FF, so it's 65520 instead of 65535 (see [#428 ](https://github.com/Mutagen-Modding/Mutagen/issues/428) for details on ResetHours magic). The following code (a replica of the float-to-ushort transform from Mutagen.Bethesda.Core/Translations/Binary/FloatBinaryTranslation.cs): `float x = 24.0f; var x2 = (ushort) Math.Round((x * 65535f) / 24f);` gives me the correct 65535, so the issue could be down the stream, in `writer.Write`, or even up the stream?

2. I tried to "overflow" ResetHours by setting it to a value that would not fit into uint16 - 32.0f. I expected Mutagen to either throw an exception or force-cap it to 24.0f/65535. Instead it just cut the higher bits not fitting into uint16 and I got 8-ish hours in the mod file. This could be very puzzling to those who don't know/remember that ResetHours are capped at 24 hours. I suggest to introduce some min-max checks in the float-to-uint function in FloatBinaryTranslation.cs. For example, if the value converted to an unsigned integer is slightly below 0.0, force it to 0.0 (because it could happen due to rounding errors in float math), but if it's significantly below 0.0, throw an exception, and the same checks for the max value of the target integer format.

**Comment by gavrant** [comment]
Some additions:
1a. In 0.40, ResetHours had the multiplier of 0.0003663003663003663. Which is 1 / 2730. And 2730 * 24 = 65520. Was it assumed at some point that max. value of uint16 is 65520, judging by how often this number appears?

1b. xEdit seems to treat ResetHours in the same way as Mutagen. It shows raw 65520 as 24.00000. And if you set it to 24.0 in Creation Kit, xEdit will show that as 24.005495. Have any parts of Mutagen originated from xEdit code?

2 . I guess, the best place for an exception on overflow would be the setter of each property that is converted from float to an uint on write, with an individual message for each of them to be understandable by anyone without studying UESP. It would require some work, and, TBH, I could live without an overflow exception. But a "force-cap" in FloatBinaryTranslation.Write is a must have, IMHO. By "force-cap" I mean something like this:
```
private float ForceCap(float value, float maxValue)
{
    if (value <= 0.0f)
        return 0.0f;
    if (value >= maxValue)
        return maxValue;
    return value;
}
```
IIRC, Creation Kit does not complain on overflow too, just caps the value under the hood (although it could be because I, as many other users of CK, have any messages turned off in it).

**Comment by Noggog** [comment]
First off, some of the changes on the previous card that was marked as complete didn't make it into `0.41`.  Part of the reason I pushed `0.41` was to publish the "stable" changes before adding in the new experimental float conversion revamps.   So the changes you're expecting should be in the upcoming `0.41.1-prxxx` release that should be later today. 

Here's the interesting commits which aren't yet included in any release
5748a9f7862851eea58f66c5aa4d24f9ae95a71c
4ab20852d6b9b353cfdb42b71628dfd60e6de18a

>  Have any parts of Mutagen originated from xEdit code?

Yes.  Most of mutagen's understanding is by looking to xEdit's definitions as reference, but it deviates when it's appropriate/helpful

> Overflow

I did add an overflow exception at time of writing to disk.  So that should throw rather than truncate going forward.
There's a bit of a tradeoff for when overflow exceptions hit.  If you do them too close to the `set` of ResetHours, for example, then mid-transformation steps can throw even if the final value would be "safe":
```cs
x.ResetHours *= 2; // Maybe would throw here if too large
x.ResetHours /= 3;
```
But, of course, delaying until time of write means its harder to track down when exactly an out of bounds value was set.  So far, mutagen has chosen to usually delay these checks until time of writing to disk

**Comment by gavrant** [comment]
OK, my bad, from looking at https://github.com/Mutagen-Modding/Mutagen/commits/dev I don't understand which commit goes where. Waiting for the next pre-release then.

> Overflow

As I said in the "additions" comment, I would be happy with just a silent "force-cap"/"normalize", without any exceptions. I don't remember how easy is to track down in the VS debugger which record throws an exception on write in Mutagen, and maybe with Synthesis it's harder to do than with bare Mutagen (I use just Mutagen, no Synthesis), but I remember reading here about someone spending hours to find which piece of their code was triggering some write exception.

**Comment by gavrant** [comment]
One more thing: ApplyTransformations from FloatBinaryTranslation.cs returns a float. I can't remember the 32-bit float format (Single/float in C# terms) off the top of my head, but according to people on the internet (stackoverflow.com and stuff), its precision goes up to 9 digits. It's enough for byte (uint8) or ushort (uint16), but UInt (uint32) can go as high as 4 billion-something, which is 10 digits. Though I don't know the use cases of float-to-uint32 in Mutagen, perhaps it's better to do all the math in ApplyTransformations in double, and return a double too?

**Comment by Noggog** [comment]
No worries!

> ResetHours = 24.0f still results in 23.99 in Creation Kit

Yeah, was poking around a little bit, and noticed that current release mutagen setting it to 24f shows 24 in xEdit.   Once the improvements are applied, it shows 24.005495 in xEdit.   

> I remember reading here about someone spending hours to find which piece of their code was triggering some write exception.

Maybe that was from a while ago, or might have been some other bug they had that was harder to track down, but writing exceptions are "enriched" to show the record that contained them, ala
https://github.com/Mutagen-Modding/Mutagen/blob/dev/Mutagen.Bethesda.Skyrim/Records/SkyrimMajorRecord_Generated.cs#L1641

> Though I don't know the use cases of float-to-uint32 in Mutagen, perhaps it's better to do all the math in ApplyTransformations in double, and return a double too?

Can look into that

**Comment by Noggog** [comment]
Try out `0.41.1-pr001` and let me know if it does any better for you or if there's more needed

**Comment by gavrant** [comment]
Tried 0.41.1-pr001.
`ResetHours = 24.0f` test worked great - got 24.00 in CK, 24.005495 in xEdit, as expected.
`ResetHours = 32.0f` threw an exception on write.

**Comment by Noggog** [comment]
If i understand correctly, the `32` is an expected overflow?
`32 * 65535 / 24 = 87380` where `87380` is larger than the two bytes of space it has

**Comment by gavrant** [comment]
Yes, it's an expected overflow exception, but I would not say that "Arithmetic operation resulted in an overflow." clearly communicates the problem. It does not tell the field name, and even if it would, it would not tell what you and me know - why 32 is illegal here.

**Comment by gavrant** [comment]
I mean, you and I know what's going here because we're digging this particular field for the last 2 or 3 days. For anyone else it would be unexpected. A "perfect" message here would be something like "ResetHours does not support values greater than 24.0f", but that would require a custom exception message for every float-to-uint field? Or maybe not, if the function gets the field name and formats the message like "{FieldName} does not support values greater than {MaxValue}".

**Comment by Noggog** [comment]
Yeah, seeing what I can do real quick

**Comment by Noggog** [comment]
1d2d45665652f1aaf9230e38d1630c4120c4a9b5
Next release should have it show exceptions like this
![image](https://user-images.githubusercontent.com/24981326/230273879-c4340b8f-ec57-4e8f-b505-7baa41150566.png)

**Comment by gavrant** [comment]
Yeah, the message looks fine now.
