### ISSUE TITLE
Is it possible hold GameRelease.ToCategory extension function for compatibility?

### ISSUE THREAD

**Issue by Odashikonbu** [Mutagen-Modding/Mutagen#459]
After latest mutagen update, existing almost patcher stopped working by "Method not found" error. I understand Synthesis can select mutagen version, but think old patcher also should get benefit from latest mutagen for example bugfix.

**Comment by Noggog** [comment]
I think this was just a result of delayed releases.  Mutagen got pushed last night, but I didn't get to pushing a paired Synthesis version until this morning.

Try using `Latest` again and it should work

**Comment by Odashikonbu** [comment]
Thank you, Worked fine as you say.
