### ISSUE TITLE
Starfield Baseline

### ISSUE THREAD

**Issue by Noggog** [Mutagen-Modding/Mutagen#482]
Get Mutagen to a baseline where it's able to passthrough test the records from the base master files, even if some of the fields are still unknown

# TODO

# WIP
## @codegangsta

# BASELINE DONE
- [x] PDCL
- [x] STDT
- [x] SDLT
- [x] TODD
- [x] DOOR
- [x] STAT
- [x] PMFT
- [x] RACE
- [x] CHAL
- [x] BMOD
- [x] SUNP
- [x] LMSW
- [x] FOGV
- [x] MTPT
- [x] WBAR
- [x] FORC
- [x] WKMF
- [x] EFSQ
- [x] PSDC
- [x] CLDF
- [x] AOPS
- [x] AMBS
- [x] RSPJ
- [x] WWED
- [x] TMLM
- [x] RFGP
- [x] STAG
- [x] RSGD
- [x] SFBK
- [x] ATMO
- [x] PCMT
- [x] MRPH
- [x] STBH
- [x] SFPC
- [x] PCBN
- [x] SPCH
- [x] LENS
- [x] TRAV
- [x] SFTR
- [x] VOLI
- [x] AAPD
- [x] SFPT
- [x] KSSM
- [x] #503
- [x] ARMO
- [x] PCCN
- [x] LGTM
- [x] MOVT
- [x] ZOOM
- [x] LVSC
- [x] STND
- [x] GCVR
- [x] OVIS
- [x] FSTP
- [x] REVB
- [x] EQUP
- [x] COLL
- [x] CLFM
- [x] NOCM
- [x] DOBJ
- [x] ARTO
- [x] SMEN
- [x] MUSC
- [x] IPCT
- [x] MAAM
- [x] SMQN
- [x] SMBN
- [x] BPTD
- [x] IPDS
- [x] CPTH
- [x] FSTS
- [x] VTYP
- [x] MESG
- [x] CAMS
- [x] MUST
- [x] ARMA
- [x] MATT
- [x] FLST
- [x] ADDN
- [x] AVIF
- [x] IMGS
- [x] WTHS
- [x] EXPL
- [x] PROJ
- [x] HAZD
- [x] EFSH
- [x] IDLM
- [x] FLOR
- [x] REGN
- [x] IMAD
- [x] IDLE
- [x] NAVI
- [x] AAMD
- [x] KEYM
- [x] GRAS
- [x] GBFM
- [x] LVLB
- [x] SPGD
- [x] MSTT
- [x] TERM
- [x] CSTY
- [x] SCEN
- [x] QUST
- [x] BMMO
- [x] LIGH
- [x] LSCR
- [x] LVLN
- [x] PKIN
- [x] FURN
- [x] INNR
- [x] PACK
- [x] GBFT
- [x] LAYR
- [x] NPC_
- [x] WRLD
- [x] STMP
- [x] WATR
- [x] CLMT
- [x] NAVM
- [x] LVLP
- [x] CONT
- [x] IRES
- [x] CNDF
- [x] PGRE
- [x] OMOD
- [x] AMMO
- [x] LCTN
- [x] CELL
- [x] BOOK
- [x] ACHR
- [x] REFR
- [x] CURV
- [x] ALCH
- [x] DIAL
- [x] WTHR
- [x] PHZD
- [x] PERK
- [x] COBJ
- [x] LGDI
- [x] WEAP
- [x] MISC
- [x] DLBR
- [x] INFO
- [x] MGEF
- [x] SECH
- [x] ENCH
- [x] CUR3
- [x] ACTI
- [x] SOUN
- [x] ASPC
- [x] SPEL
- [x] AMDL
- [x] AORU
- [x] BNDS
- [x] #492
- [x] OTFT
- [x] LTEX
- [x] ANIO
- [x] SCOL
- [x] GMST
- [x] KYWD
- [x] FFKW
- [x] LVLI
- [x] LCRT
- [x] AACT
- [x] TRNS
- [x] TXST
- [x] GLOB
- [x] DMGT
- [x] CLAS
- [x] FACT
- [x] AFFE
- [x] HDPT
- [x] PNDT
- [x] SDSA
- [x] AVMD
- [x] AOPF
- [x] PTST
- [x] DEBR
- [x] OSWP

**Comment by codegangsta** [comment]
Thanks for this awesome project! I'm currently working on parsing `TMLM` and a couple other records on the todo list. Should have a PR up by the end of the week!

**Comment by Noggog** [comment]
Thanks @codegangsta !  I sent you a Mutagen org invite if you want it.  Should give you the ability to modify the OP post and drag things around at that point

**Comment by codegangsta** [comment]
I accepted the invite! Hopefully a PR will be up tomorrow. It doesn't look like I'm able to edit this issue though

**Comment by Noggog** [comment]
Ah, i think i had to add you to a team
