### ISSUE TITLE
DESC Record is improperly localised when NULL from Starfield Perk Records

### ISSUE THREAD

**Issue by Pickysaurus** [Mutagen-Modding/Mutagen#499]
When a perk has a description of NULL (e.g.)
![image](https://github.com/Mutagen-Modding/Mutagen/assets/31670524/da5ed48b-c54f-4a38-a23d-5a2a6d3cddfe)

This is not properly carried over into the `.strings` files on building a localised plugin. 

The English `.strings` file correctly skips this entry but other locales (e.g. French, Spanish) get an ID added to the `.strings` file which results in a "LOOKUP FAILED" error in xTranslator. 

The behaviour for blanks strings should be consistent across all locales.

**Comment by Noggog** [comment]
@Pickysaurus is this still an issue in the latest spriggits?  Havent had a chance to dig myself yet

**Comment by Noggog** [comment]
Going to close for now.   Please reopen if it's still biting the latest setups
