### ISSUE TITLE
Issue with plugin version 1.71; Plugins using the new Form space do not get copied or saved correctly when saving a plugin

### ISSUE THREAD

**Issue by Michael-wigontherun** [Mutagen-Modding/Mutagen#509]
1.71 opened up the door for more esl forms, you have definitely been told about this repeatedly by others and excuse me if I am duplicating this issue as well, especially if this is specifically a Synthesis issue but it seems like its more an issue with Mutegen.

When Mutagen copies a form from that new esl space from 1.71. It looses the ModKey for the original plugin and defaults to Skyrim.esm.
Synthesis generated patch:

![image](https://github.com/Mutagen-Modding/Mutagen/assets/43317302/09a080f1-4c1d-443e-8e44-a709d35c188c)
Original plugin, "Skyrim Food Expansion.esp" [https://www.nexusmods.com/skyrimspecialedition/mods/110935](https://www.nexusmods.com/skyrimspecialedition/mods/110935):

![image](https://github.com/Mutagen-Modding/Mutagen/assets/43317302/4623ba4c-1aa8-4430-968f-f28d3d235141)

And it becomes especially dangerous if it happens to be a FormID that actually overlaps with Skyrim.esm

Synthesis generated patch:

![image](https://github.com/Mutagen-Modding/Mutagen/assets/43317302/c0b6c131-50bc-4432-91ec-8550541c2bbc)
Skyrim.esm

![image](https://github.com/Mutagen-Modding/Mutagen/assets/43317302/8b29969c-a704-403c-be54-92bed9a310c3)
Original plugin, "Skyrim Food Expansion.esp" [https://www.nexusmods.com/skyrimspecialedition/mods/110935](https://www.nexusmods.com/skyrimspecialedition/mods/110935):

![image](https://github.com/Mutagen-Modding/Mutagen/assets/43317302/c245f6e6-8020-405b-990e-928f80918ed2)

[Skyrim Food Expansion](https://www.nexusmods.com/skyrimspecialedition/mods/110935) and my [SynNotSoSalty](https://github.com/Michael-wigontherun/SynNotSoSalty) patcher were used if you wish to test and replicate it

I am using Synthesis version 0.26. And my patcher, SynNotSoSalty is already using the latest version of Mutegen v0.42.0 and Synthesis v0.26.0. I would consider this an urgent issue. And again I am sorry if this is a duplicate issue, I could not locate another issue with this direct issue.

**Comment by Noggog** [comment]
I think this is just because you were running /w mutagen versions that only output 1.7 headers, but Synthesis was pulling in mods /w 1.71 headers as inputs

Mutagen v0.43 and Synthesis v0.27 should hopefully fix your issue
