### ISSUE TITLE
String breaks due to consecutive patches

### ISSUE THREAD

**Issue by Xanardi** [Mutagen-Modding/Mutagen#517]
When I run multiple patcher sequences and output Synthesis.esp,
the strings (Japanese) are partially broken.

I think that the mixture of Localized and Unlcalized patcher target ESP is not good.

For example, this happens when the following patches are executed successively.
* [AI-Overhaul-Patcher](https://github.com/Excinerus/AI-Overhaul-Patcher)
* [NpcProtector](https://github.com/alsa64/NpcProtector)

If you separate the group of patches, the strings will not be broken.

**Comment by Noggog** [comment]
Sorry for the long delay! 

I think this card has perhaps been opened in the wrong repo?   Feels more appropriate to be in 
https://github.com/Mutagen-Modding/Synthesis

Can you reopen the card there, and also include your specific settings that you have selected for the language settings of Synthesis?
https://github.com/Mutagen-Modding/Synthesis/wiki/Language-Settings

It's definitely a complex topic, and things can get borked if everything isn't set up exactly as it needs to be.   I hope to improve the docs for this more over time to help people make the right selections.

See you over on the synthe repo!

**Comment by Xanardi** [comment]
Thank you.
I reviewed the settings and was able to resolve the issue.

Thanks for the Wiki referral.
That's exactly what I was looking for.
