### ISSUE TITLE
LinkCache.GetNth

### ISSUE THREAD

**Issue by Noggog** [Mutagen-Modding/Mutagen#61]
Some way to dig deeper to retrieve a record besides the winner override

**Comment by Deigue** [comment]
I can see myself using this function alot in hindsight, marking this as well. In the interest of getting more details, specifics ... and consideration of tackling myself if I can figure it out.

**Comment by Noggog** [comment]
This issue would be related to the whole concept of digging -past- the winning override.  so this could take a few forms:
- `T GetNth(FormKey key, int depth)`
   Would throw if you queried a for the 5th mod if there was only 4 that had the record.
   Might need to be paired with GetRecordCount or something?  Overall though, i favor:
- `IEnumerable<T> LookupAll(FormKey key)`
   This one is interesting, as it would first return the winning override in the enumerable, but as the user enumerated, it would search deeper and deeper, until it found the source mod, which would be the end of the enumerable.  The cool part would be that leveraging lazy enumerable concepts, if the user stopped enumerating at half depth, it wouldn't need to search any farther.  It would only search as deep as it was enumerated.

The above calls would need to support all the typing alternates:
- Naked (all major recs)
- Type parameter
- Type generic

**Comment by Deigue** [comment]
Sounds good.
Yeah, I think I like the second one `LookupAll` better, seems more intuitive to use. When would one ask GetNth(key, 15) for example anyway ... Enumerable sounds like it does more and gives the caller some choices later too which I like.

Any other peculiarities? I can just make use of whatever I have to work with in LinkCache implementors like Mutable/Immutable<LoadOrder>LinkCache classes, from what I can remember there was already tons of referential info there to implement this quite easily, but you know better than me.

Let me know, if it sounds simple enough, I will take stab at this one. Seems doable.

**Comment by Noggog** [comment]
The complexity in this one is just refactoring the optimized internals of ImmutableLoadOrderLinkCache to retain the current speed for normal lookups, while adding the additional functionality.  Right now it is heavily optimized for finding the winning override, and doesn't have much internal mechanics for keeping track of more than one record per formkey.

Basically its logic is this:
- User queries for FormKey 123456:Skyrim of type Npc
- It looks up the Npc type in the InternalTypedCache dictionary and doesn't find one
- It then iterates over the first mod, grabbing all NPC records, putting them in the InternalTypedCache.  
- It then queries the InternalTypedCache associated with NPCs for the FormKey
- If found, returns.  If not, it moves onto the next mod, adding its Npcs to the InternalTypedCache, repeat.
- On second query, it's a simple dictionary lookup
- If not found in the cache, still, that just means the first query might've stopped at a shallow depth, and this query needs to look further.  It's tracking the depth it looked for NPCs, so it can just continue from there.
- Only if we've gotten to a depth of the whole load order do we say we can't find the FormKey

Those mechanics don't really take into account that a single FormKey might have several associated records.  It all eventually funnels into a Dictionary<FormKey, Record>.  So you'll need to gut and rethink the structure a bit

**Comment by Noggog** [comment]
95aaec7ca2956c01537bd04aa47d87b2538e1646
